spring:
  application:
    name: simple-service
  profiles:
    active:
    - default
  cloud:
    config:
      enabled: true
eureka:
  client:
    enabled: false
#disable basic authentication as spring cloud enables it by default
security:
  basic:
    enabled: false
endpoints:
  routes:
    sensitive: false
management:
  security:
    enabled: false
server:
  port: 8081
