server:
  port: 8081
ribbon:
  eureka:
    enabled: true
info:
  artifactId: "@project.artifactId@"
  description: "@project.description@"
  version: "@project.version@"
security:
  basic:
    enabled: false
management:
  security:
    enabled: false
